/*Auto generated by Kirby v1.0.0 - Wed Mar 14 2018 23:27:37 GMT-0700 (PDT)
  czlab.elmo.ecs.core
{"doc" "" "author" "Kenneth Leung"}
*/

const ky = require("kirby");
const Atom = ky["Atom"];
const atom = ky["atom"];
const swap_BANG = ky["swap_BANG"];
const partition = ky["partition"];
const conj_BANG = ky["conj_BANG"];
const disj_BANG = ky["disj_BANG"];
const kirbystdlibref = require("kirby");
const __module_namespace__ = "czlab.elmo.ecs.core";
////////////////////////////////////////////////////////////////////////////////
//fn: [createPool] in file: entity-manager.ky, line: 17
const createPool = function(name, ctor, batch) {
  return atom({
    "name": name,
    "size": 0,
    "next": 0,
    "slots": [],
    "ctor": ctor,
    "batch": batch
  });
};
////////////////////////////////////////////////////////////////////////////////
//fn: [getPoolSize] in file: entity-manager.ky, line: 23
const getPoolSize = function(pool) {
  return kirbystdlibref.getProp(pool.value, "size");
};
////////////////////////////////////////////////////////////////////////////////
//fn: [getPoolUsed] in file: entity-manager.ky, line: 26
const getPoolUsed = function(pool) {
  return kirbystdlibref.getProp(pool.value, "next");
};
////////////////////////////////////////////////////////////////////////////////
//fn: [takeFromPool] in file: entity-manager.ky, line: 29
const takeFromPool = function(pool) {
  let ret = null;
  swap_BANG(pool, function(root) {
    let size = kirbystdlibref.getProp(root, "size");
    let next = kirbystdlibref.getProp(root, "next");
    let slots = kirbystdlibref.getProp(root, "slots");
    let batch = kirbystdlibref.getProp(root, "batch");
    let ctor = kirbystdlibref.getProp(root, "ctor");
    if ( (next >= size) ) {
      for (let x = 0, GS__4 = batch, ____break = false; ((!____break) && (x < GS__4)); x = (x + 1)) {
        conj_BANG(slots, ctor());
      }
      (root["size"] = (batch + size));
    }
    (ret = slots[next]);
    (ret["status"] = true, ret["slot"] = next);
    (
    root["next"] = (next + 1));
    return root;
  });
  return ret;
};
////////////////////////////////////////////////////////////////////////////////
//fn: [returnToPool] in file: entity-manager.ky, line: 43
const returnToPool = function(obj, pool) {
  return swap_BANG(pool, function(root) {
    let next = kirbystdlibref.getProp(root, "next");
    let slots = kirbystdlibref.getProp(root, "slots");
    if (obj.status) {
      (
      root["next"] = (next - 1));
      let tail = slots[root.next];
      let slot_QUOT = kirbystdlibref.getProp(tail, "slot");
      let epos_QUOT = kirbystdlibref.getProp(obj, "slot");
      (slots[root.next] = obj, slots[epos_QUOT] = tail);
      (
      tail["slot"] = epos_QUOT);
      (obj["slot"] = slot_QUOT, obj["status"] = false);
    }
    return root;
  });
};
////////////////////////////////////////////////////////////////////////////////
//fn: [createECS] in file: entity-manager.ky, line: 60
const createECS = function() {
  return atom((new Map([["entities",(new Set([]))], ["registry",(new Map([]))], ["data",(new Map([]))], ["systems", []], ["uid", 1]])));
};
////////////////////////////////////////////////////////////////////////////////
//fn: [genUid] in file: entity-manager.ky, line: 67
const genUid = function(ecs) {
  let ret = 0;
  swap_BANG(ecs, function(root) {
    let uid = kirbystdlibref.getProp(root, "uid");
    (
    ret = uid);
    return (kirbystdlibref.assoc_BANG(root, "uid", (uid + 1)));
  });
  return ["e@", ret].join("");
};
////////////////////////////////////////////////////////////////////////////////
//fn: [createEntity] in file: entity-manager.ky, line: 75
const createEntity = function(ecs, componentId) {
  let moreIds = Array.prototype.slice.call(arguments, 2);
  return (function() {
    let entity = genUid(ecs);
    addToEntity.apply(this, [ecs, entity].concat([componentId].concat(moreIds)));
    swap_BANG(ecs, function(root) {
      let entities = kirbystdlibref.getProp(root, "entities");
      conj_BANG(entities, entity);
      return root;
    });
    return entity;
  }).call(this);
};
////////////////////////////////////////////////////////////////////////////////
//fn: [removeEntity] in file: entity-manager.ky, line: 85
const removeEntity = function(ecs, entity) {
  let more = Array.prototype.slice.call(arguments, 2);
  let ents = [entity].concat(more);
  swap_BANG(ecs, function(root) {
    let entities = kirbystdlibref.getProp(root, "entities");
    let data = kirbystdlibref.getProp(root, "data");
    let registry = kirbystdlibref.getProp(root, "registry");
    Array.from(registry.keys()).forEach(function() {
      let ____args = Array.prototype.slice.call(arguments);
      return (function() {
        let GS__9 = kirbystdlibref.getProp(data, ____args[0]);
        let co = GS__9;
        return ((((typeof (GS__9) === "undefined")) || ((GS__9 === null))) ?
          null :
          ents.forEach(function() {
            let ____args = Array.prototype.slice.call(arguments);
            return kirbystdlibref.dissoc_BANG(co, ____args[0]);
          }));
      }).call(this);
    });
    ents.forEach(function() {
      let ____args = Array.prototype.slice.call(arguments);
      return disj_BANG(entities, ____args[0]);
    });
    return root;
  });
  return ecs;
};
////////////////////////////////////////////////////////////////////////////////
//fn: [addComponent] in file: entity-manager.ky, line: 95
const addComponent = function(ecs, id, component) {
  let more = Array.prototype.slice.call(arguments, 3);
  swap_BANG(ecs, function(root) {
    let registry = kirbystdlibref.getProp(root, "registry");
    (kirbystdlibref.assoc_BANG(registry, id, component));
    partition(2, more).forEach(function(GS__11) {
      let a = kirbystdlibref.getIndex(GS__11, 0);
      let b = kirbystdlibref.getIndex(GS__11, 1);
      return (kirbystdlibref.assoc_BANG(registry, a, b));
    });
    return root;
  });
  return ecs;
};
////////////////////////////////////////////////////////////////////////////////
//fn: [removeComponent] in file: entity-manager.ky, line: 103
const removeComponent = function(ecs, id) {
  let more = Array.prototype.slice.call(arguments, 2);
  return swap_BANG(ecs, function(root) {
    let data = kirbystdlibref.getProp(root, "data");
    let registry = kirbystdlibref.getProp(root, "registry");
    kirbystdlibref.dissoc_BANG(registry, id);
    kirbystdlibref.dissoc_BANG(data, id);
    more.forEach(function(a) {
      kirbystdlibref.dissoc_BANG(registry, a);
      return kirbystdlibref.dissoc_BANG(data, a);
    });
    return root;
  });
};
////////////////////////////////////////////////////////////////////////////////
//fn: [addToEntity] in file: entity-manager.ky, line: 113
const addToEntity = function(ecs, entity) {
  let componentIds = Array.prototype.slice.call(arguments, 2);
  return swap_BANG(ecs, function(root) {
    let data = kirbystdlibref.getProp(root, "data");
    let registry = kirbystdlibref.getProp(root, "registry");
    let ctor = null;
    let co = null;
    componentIds.forEach(function(cid) {
      (
      ctor = kirbystdlibref.getProp(registry, cid));
      if ( (!ctor) ) {
        throw new Error(["Unknown component ", cid].join(""));
      } else {
        null;
      }
      if ( (!data.has(cid)) ) {
        (kirbystdlibref.assoc_BANG(data, cid, (new Map([]))));
      } else {
        null;
      }
      (co = ctor());
      (
      co["____entity"] = entity);
      return (kirbystdlibref.assoc_BANG(kirbystdlibref.getProp(data, cid), entity, co));
    });
    return root;
  });
};
////////////////////////////////////////////////////////////////////////////////
//fn: [removeFromEntity] in file: entity-manager.ky, line: 126
const removeFromEntity = function(ecs, entity) {
  let componentIds = Array.prototype.slice.call(arguments, 2);
  return swap_BANG(ecs, function(root) {
    let data = kirbystdlibref.getProp(root, "data");
    componentIds.forEach(function() {
      let ____args = Array.prototype.slice.call(arguments);
      return (function() {
        let GS__15 = kirbystdlibref.getProp(data, ____args[0]);
        let c = GS__15;
        return ((((typeof (GS__15) === "undefined")) || ((GS__15 === null))) ?
          null :
          kirbystdlibref.dissoc_BANG(c, entity));
      }).call(this);
    });
    return root;
  });
};
////////////////////////////////////////////////////////////////////////////////
//fn: [getDataForEntity] in file: entity-manager.ky, line: 133
const getDataForEntity = function(ecs, entity, componentId) {
  let d = kirbystdlibref.getProp(ecs.value, "data");
  let c = kirbystdlibref.getProp(d, componentId);
  return (c ?
    kirbystdlibref.getProp(c, entity) :
    null);
};
////////////////////////////////////////////////////////////////////////////////
//fn: [updateEntity] in file: entity-manager.ky, line: 139
const updateEntity = function(ecs, entity, componentId, func) {
  return swap_BANG(ecs, function(root) {
    let data = kirbystdlibref.getProp(root, "data");
    let GS__17 = getDataForEntity(ecs, entity, componentId);
    let c = GS__17;
    if ( (((typeof (GS__17) === "undefined")) || ((GS__17 === null))) ) {
      null;
    } else {
      func(c);
    }
    return root;
  });
};
////////////////////////////////////////////////////////////////////////////////
//fn: [getComponentsData] in file: entity-manager.ky, line: 146
const getComponentsData = function(ecs, componentId) {
  let d = kirbystdlibref.getProp(ecs.value, "data");
  let c = kirbystdlibref.getProp(d, componentId);
  return (c ?
    Array.from(c.values()) :
    []);
};
////////////////////////////////////////////////////////////////////////////////
//fn: [getComponentKeys] in file: entity-manager.ky, line: 152
const getComponentKeys = function(ecs) {
  return Array.from(kirbystdlibref.getProp(ecs.value, "registry").keys());
};
////////////////////////////////////////////////////////////////////////////////
//fn: [findComponent] in file: entity-manager.ky, line: 155
const findComponent = function(ecs, componentId) {
  return kirbystdlibref.getProp(kirbystdlibref.getProp(ecs.value, "registry"), componentId);
};
////////////////////////////////////////////////////////////////////////////////
//fn: [componentInEntity?] in file: entity-manager.ky, line: 159
const componentInEntity_QMRK = function(ecs, entity, componentId) {
  let moreIds = Array.prototype.slice.call(arguments, 3);
  let d = kirbystdlibref.getProp(ecs.value, "data");
  return (![componentId].concat(moreIds).some(function() {
    let ____args = Array.prototype.slice.call(arguments);
    return nichts_QMRK(kirbystdlibref.getProp(d, ____args[0]));
  }));
};
////////////////////////////////////////////////////////////////////////////////
//fn: [addTemplate] in file: entity-manager.ky, line: 165
const addTemplate = function(ecs, id, template) {
  let more = Array.prototype.slice.call(arguments, 3);
  swap_BANG(ecs, function(root) {
    let templates = kirbystdlibref.getProp(root, "templates");
    partition(2, [id, template].concat(more)).forEach(function(GS__19) {
      let a = kirbystdlibref.getIndex(GS__19, 0);
      let b = kirbystdlibref.getIndex(GS__19, 1);
      return (kirbystdlibref.assoc_BANG(templates, a, b));
    });
    return root;
  });
  return ecs;
};
////////////////////////////////////////////////////////////////////////////////
//fn: [getTemplateKeys] in file: entity-manager.ky, line: 173
const getTemplateKeys = function(ecs) {
  return Array.from(kirbystdlibref.getProp(ecs.value, "templates").keys());
};
////////////////////////////////////////////////////////////////////////////////
//fn: [findTemplate] in file: entity-manager.ky, line: 176
const findTemplate = function(ecs, templateId) {
  return kirbystdlibref.getProp(kirbystdlibref.getProp(ecs.value, "templates"), templateId);
};
////////////////////////////////////////////////////////////////////////////////
//fn: [removeTemplate] in file: entity-manager.ky, line: 180
const removeTemplate = function(ecs, id) {
  let moreIds = Array.prototype.slice.call(arguments, 2);
  swap_BANG(ecs, function(root) {
    let templates = kirbystdlibref.getProp(root, "templates");
    [id].concat(moreIds).forEach(function() {
      let ____args = Array.prototype.slice.call(arguments);
      return kirbystdlibref.dissoc_BANG(templates, ____args[0]);
    });
    return root;
  });
  return ecs;
};
////////////////////////////////////////////////////////////////////////////////
//fn: [createTemplateEntity] in file: entity-manager.ky, line: 187
const createTemplateEntity = function(ecs, id) {
  let entity = null;
  swap_BANG(ecs, function(root) {
    let templates = kirbystdlibref.getProp(root, "templates");
    let t = kirbystdlibref.getProp(templates, id);
    (entity = createEntity.apply(this, seq(t.components)));
    if (( (typeof (t.initor) === "function") )) {
      t.initor(ecs, entity);
    }
    return root;
  });
  return entity;
};
////////////////////////////////////////////////////////////////////////////////
//fn: [addSystem] in file: entity-manager.ky, line: 198
const addSystem = function(ecs, system) {
  return swap_BANG(ecs, function(root) {
    let systems = kirbystdlibref.getProp(root, "systems");
    conj_BANG(systems, system);
    return root;
  });
};
////////////////////////////////////////////////////////////////////////////////
//fn: [removeSystem] in file: entity-manager.ky, line: 204
const removeSystem = function(ecs, system) {
  return swap_BANG(ecs, function(root) {
    let systems = kirbystdlibref.getProp(root, "systems");
    let i = systems.indexOf(system);
    if ( (!((i < 0))) ) {
      systems.splice(i, 1);
    } else {
      null;
    }
    return root;
  });
};
////////////////////////////////////////////////////////////////////////////////
//fn: [updateECS] in file: entity-manager.ky, line: 212
const updateECS = function(ecs, dt) {
  return kirbystdlibref.getProp(ecs.value, "systems").forEach(function() {
    let ____args = Array.prototype.slice.call(arguments);
    return ____args[0].update(dt);
  });
};
module.exports = {
  da57bc0172fb42438a11e6e8778f36fb: {
    ns: "czlab.elmo.ecs.core",
    macros: {}
  },
  createPool: createPool,
  getPoolSize: getPoolSize,
  getPoolUsed: getPoolUsed,
  takeFromPool: takeFromPool,
  returnToPool: returnToPool,
  createECS: createECS,
  createEntity: createEntity,
  removeEntity: removeEntity,
  addComponent: addComponent,
  removeComponent: removeComponent,
  addToEntity: addToEntity,
  removeFromEntity: removeFromEntity,
  getDataForEntity: getDataForEntity,
  updateEntity: updateEntity,
  getComponentsData: getComponentsData,
  getComponentKeys: getComponentKeys,
  findComponent: findComponent,
  componentInEntity_QMRK: componentInEntity_QMRK,
  addTemplate: addTemplate,
  getTemplateKeys: getTemplateKeys,
  findTemplate: findTemplate,
  removeTemplate: removeTemplate,
  createTemplateEntity: createTemplateEntity,
  addSystem: addSystem,
  removeSystem: removeSystem,
  updateECS: updateECS
};