/*Auto generated by Kirby v1.0.0 - Mon Jan 08 2018 16:46:41 GMT-0800 (PST)
  poo.face
(null)
*/

const k = require("kirby");
const kirbystdlibref = require("kirby");
(function(mo) {
  let bind = mo["bind"];
  let unit = mo["unit"];
  let zero = mo["zero"];
  let ret = function() {
    let ____args = Array.prototype.slice.call(arguments);
    return ((kirbystdlibref.nichts_QUERY(____args[0]) && ((typeof (zero) !== "undefined"))) ?
      zero :
      unit(____args[0]));
  };
  return bind(1, function(a) {
    return bind((a * 2), function(b) {
      return (function() {
        return ret((a + b));
      }).call(this);
    });
  });
})(k.m_DASH_maybe)
module.exports = {
  da57bc0172fb42438a11e6e8778f36fb: {
    ns: "poo.face",
    macros: {}
  }
};