/*Auto generated by Kirby v1.0.0 - Tue Apr 10 2018 22:15:33 GMT-0700 (PDT)
  czlab.elmo.ecs.core
{"doc" "" "author" "Kenneth Leung"}
*/

const ky = require("kirby");
const _atom_ = ky["atom"];
const Atom = ky["Atom"];
const swap_BANG = ky["swap_BANG"];
const conj_BANG = ky["conj_BANG"];
const disj_BANG = ky["disj_BANG"];
const kirbystdlibref = require("kirby");
const __module_namespace__ = "czlab.elmo.ecs.core";
////////////////////////////////////////////////////////////////////////////////
//fn: [xmod] in file: x.ky, line: 20
//Return the proper mathematical modulo of x mod N.
const xmod = function(x, N) {
  return (((x < 0)) ?
    (x - (-1 * (N + (N * Math.floor(((-1 * x) / N)))))) :
    (x % N));
};
////////////////////////////////////////////////////////////////////////////////
//fn: [xxx] in file: x.ky, line: 26
const xxx = function(a, b) {
  let x = function() {};
  return null;
};
module.exports = {
  da57bc0172fb42438a11e6e8778f36fb: {
    ns: "czlab.elmo.ecs.core",
    vars: ["xmod", "xxx"],
    macros: {
      "poo": "(macro* poo (a b & more) (syntax-quote (.add (unquote a) (unquote b) (splice-unquote more))))"
    }
  },
  xmod: xmod,
  xxx: xxx
};