/*Auto generated by Kirby - v1.0.0 undefined Sat Oct 28 2017 23:19:10 GMT-0700 (PDT)*/

let xxx_PERCppp;
xxx_PERCppp= 3;
;
//
function gensym() {
let G____1=Array.prototype.slice.call(arguments,0);
let G____2= G____1;
let pfx;
pfx=G____2[0];
let x;
x= gensym_counter;
;
++gensym_counter;
return [std.maybe(pfx,"G____"),x].join("");
}

